src/Clayton/Models/SiteSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clayton.Models
{
    public class SiteSettings
    {
        public int SiteSettingsId { get; set; }

        public string Name { get; set; }

        public string Slogan { get; set; }

    }
}

src/Clayton/Controllers/SiteSettingsController.cs
using Clayton.Models;
using Clayton.Models.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clayton.Controllers
{
    [Authorize]
    public class SiteSettingsController : Controller
    {
        private readonly ISiteSettingsRepository _siteSettingsRepository;

        public SiteSettingsController(ISiteSettingsRepository siteSettingsRepository)
        {
            _siteSettingsRepository = siteSettingsRepository;
        }

        public IActionResult Index()
        {
            SiteSettings settings = _siteSettingsRepository.GetSettings();
            if(settings == null)
            {
                settings = new SiteSettings();
            }
            return View(settings);
        }

        [HttpPost]
        public IActionResult Save(SiteSettings settings)
        {
            _siteSettingsRepository.SaveSettings(settings);
            return RedirectToAction("Index");
        }

    }
}

src/Clayton/Views/SiteSettings/Index.cshtml
@model Clayton.Models.SiteSettings

<div id="DashboardContainer">
    <h3>Site Settings</h3>

    <form asp-controller="SiteSettings" asp-action="Save" method="post" role="form" id="SiteSettingsForm">

        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <div>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Slogan" class="control-label"></label>
            <div>
                <input id="PostSlug" asp-for="Slogan" class="form-control" />
                <span asp-validation-for="Slogan" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div>
                <input type="submit" class="btn btn-primary" value="Save Settings" />
            </div>
        </div>

    </form>


</div>