src/Clayton/Models/Enhancement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Clayton.Models
{
    public class Enhancement
    {
        public int EnhancementId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Content { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? CompletedDate { get; set; }
        public ICollection<EnhancementProgress> EnhancementProgress { get; set; }
    }
}

src/Clayton/Models/EnhancementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clayton.Models
{
    public class EnhancementViewModel
    {
        public IEnumerable<Enhancement> Enhancements { get; set; }
    }
}

src/Clayton/Models/ViewModels/EnhancementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clayton.Models.ViewModels
{
    public class EnhancementViewModel
    {
        public IEnumerable<Enhancement> Enhancements { get; set; }
    }
}

src/Clayton/Controllers/EnhancementController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Clayton.Models;
using Clayton.Models.Reposistories;
using Clayton.Models.ViewModels;

namespace Clayton.Controllers
{
    [Authorize]
    public class EnhancementController : Controller
    {
        private readonly IEnhancementRepository _enhancementRepository;

        public EnhancementController(IEnhancementRepository enhancementRepository)
        {
            _enhancementRepository = enhancementRepository;
        }

        public IActionResult Index()
        {
            EnhancementViewModel model = new EnhancementViewModel();
            model.Enhancements = _enhancementRepository.GetAll().OrderByDescending(x => x.CreateDate);
            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Enhancement enhancement)
        {
            if (!ModelState.IsValid)
            {
                return View(enhancement);
            }

            Enhancement saved = _enhancementRepository.Create(enhancement);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Enhancement enhancement = _enhancementRepository.GetById(id);
            return View(enhancement);
        }

        [HttpPost]
        public IActionResult Edit(Enhancement enhancement)
        {
            if (!ModelState.IsValid)
            {
                return View(enhancement);
            }
            _enhancementRepository.Edit(enhancement);
            return RedirectToAction("Index");
        }
    }
}

src/Clayton/Views/Enhancement/Add.cshtml
@model Clayton.Models.Enhancement

<form asp-controller="Enhancement" asp-action="Add" method="post" role="form" id="EnhancementAddForm">
    <h4>Add New Enhancement</h4>

    @* There is a bug with ASP.Net Core 1.0.0 *@
    @*https://github.com/aspnet/Mvc/issues/4989*@
    @*<div asp-validation-summary="All" class="text-danger"></div>*@

    @if (!@ViewData.ModelState.IsValid)
    {
        var errors = ViewData.ModelState.Values.Select(item => item.Errors.FirstOrDefault()?.ErrorMessage).Where(item => item != null);
        <div class="alert alert-danger">
            <span>There are problems with your input:</span>
            <ul>
                @foreach (var error in errors)
                {
                    <li>@error</li>
                }
            </ul>
        </div>
    }


    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <div>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Content" class="control-label"></label>
        <div>
            <textarea asp-for="Content" class="form-control tinyeditor" rows="10"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div>
            <input type="submit" class="btn btn-primary" value="Save New Enhancement" />
        </div>
    </div>

</form>

src/Clayton/Views/Enhancement/Edit.cshtml
@model Clayton.Models.Enhancement

<form asp-controller="Enhancement" asp-action="Edit" method="post" role="form" id="EnhancementEditForm">
    <h4>Update Enhancement</h4>

    @* There is a bug with ASP.Net Core 1.0.0 *@
    @*https://github.com/aspnet/Mvc/issues/4989*@
    @*<div asp-validation-summary="All" class="text-danger"></div>*@

    @if (!@ViewData.ModelState.IsValid)
    {
        var errors = ViewData.ModelState.Values.Select(item => item.Errors.FirstOrDefault()?.ErrorMessage).Where(item => item != null);
        <div class="alert alert-danger">
            <span>There are problems with your input:</span>
            <ul>
                @foreach (var error in errors)
                {
                    <li>@error</li>
                }
            </ul>
        </div>
    }

    @Html.HiddenFor(x => x.EnhancementId)

    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <div>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Content" class="control-label"></label>
        <div>
            <textarea asp-for="Content" class="form-control tinyeditor" rows="10"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div>
            <input type="submit" class="btn btn-primary" value="Update Enhancement" />
        </div>
    </div>

</form>

src/Clayton/Views/Enhancement/Index.cshtml
@model Clayton.Models.ViewModels.EnhancementViewModel

<h3>Enhancements planned for project</h3>


<p>I have big ideas; good ideas; huge ideas as Trump would say. However I often forget about them when I move from project to project. This page will help me
    keep track of all of the improvements I want to eventually make to this application.</p>

<a class="btn btn-primary dashboardBtn" asp-controller="Enhancement" asp-action="Add">Add Enhancement</a>



@foreach (var enhancement in Model.Enhancements)
{
    <div class="alert alert-info">
        @enhancement.Title
        <a asp-controller="Enhancement" asp-action="Edit" asp-route-id="@enhancement.EnhancementId">Edit</a>
    </div>
    <div class="enhancementContent">
        @Html.Raw(enhancement.Content)
    </div>
    
}