src/Clayton/Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Clayton.Controllers
{
    [Authorize]
    public class LabController : Controller
    {
        private IHostingEnvironment _environment;

        public LabController(IHostingEnvironment environment)
        {
            _environment = environment;
        }

        [HttpGet]
        public IActionResult UploadImage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadImage(ICollection<IFormFile> files)
        {
            var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }
                }
            }
            return View();
        }
    }
}

src/Clayton/Views/Lab/UploadImage.cshtml
@{ 
    Layout = "_LabLayout";
}

<form method="post" asp-action="UploadImage" asp-controller="Lab" enctype="multipart/form-data">
    <div class="form-group">
        <input class="form-control" type="file" name="files" multiple />
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
</form>